[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

opacity = 0.92
blur = true

title = ""
decorations = "none"

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 15.0
