# --- ОКНО ТЕРМИНАЛА ---
[window]
padding.x = 20
padding.y = 20
opacity = 0.92
blur = true
title = ""
decorations = "none"

# --- ШРИФТ ---
[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 15.0

# --- ОКРУЖЕНИЕ ---
[env]
TREM = "xtrem-256color"